# -*- coding: utf-8 -*-
"""Utility.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1582JRTcMH0n9ZJEanfzp0aSOYFzW9iqE
"""

import pickle
import os

def save_model(model, filename, model_dir="models"):
    """
    Saves a trained model to a file.
    Handles both scikit-learn and Keras models.
    """
    if not os.path.exists(model_dir):
        os.makedirs(model_dir)

    filepath = os.path.join(model_dir, filename)

    if hasattr(model, 'save'): # Keras model
        model.save(filepath)
    else: # Scikit-learn model
        with open(filepath, 'wb') as f:
            pickle.dump(model, f)

    print(f"Model saved to {filepath}")

def load_model(filename, model_dir="models"):
    """

    Loads a model from a file.
    Handles both scikit-learn and Keras models.
    """
    filepath = os.path.join(model_dir, filename)

    try:
        from tensorflow.keras.models import load_model as keras_load_model
        # Try loading as Keras model first
        model = keras_load_model(filepath)
        print(f"Keras model loaded from {filepath}")
        return model
    except Exception:
        # Fallback to pickle for scikit-learn models
        with open(filepath, 'rb') as f:
            model = pickle.load(f)
        print(f"Scikit-learn model loaded from {filepath}")
        return model